# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ignat', '0004_projectmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('priority', models.IntegerField()),
                ('estimate', models.IntegerField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ignat.Person')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ignat.Person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ignat.Project')),
            ],
        ),
    ]
