# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignat', '0007_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
